image: maven:3.8.3-openjdk-17

pipelines:
  branches:
    dev:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
    release/tst:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - mvn -B verify --file pom.xml
        - step:
            name: Create artifact
            script:
              - tar czfv tst-apple-juice-auth.tgz pom.xml system.properties src/
            artifacts:
              - tst-apple-juice-auth.tgz
        - step:
            name: Deploy to test server
            deployment: test
            script:
              - echo "Deploying to test environment"
              - pipe: atlassian/heroku-deploy:2.0.0
                variables:
                  HEROKU_API_KEY: $HEROKU_API_KEY
                  HEROKU_APP_NAME: $HEROKU_APP_NAME
                  ZIP_FILE: "tst-apple-juice-auth.tgz"